kind: Deployment
apiVersion: apps/v1
metadata:
  name: baemincrypto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baemincrypto
  template:
    metadata:
      name: baemincrypto
      labels:
        app: baemincrypto
    spec:
      containers:
        - name: baemincrypto
          image: baemincrypto
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
            - containerPort: 8080
              protocol: TCP
        - name: baemincrypto-grpcgateway
          image: baemincrypto-grpcgateway
          resources:
            limits:
              memory: 128Mi
              cpu: "0.5"
            requests:
              memory: 64Mi
              cpu: "0.2"
          ports:
            - containerPort: 18080
              protocol: TCP
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: ghcr
