kind: Deployment
apiVersion: apps/v1
metadata:
  name: baemincrypto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baemincrypto
  template:
    metadata:
      name: baemincrypto
      labels:
        app: baemincrypto
    spec:
      containers:
        - name: baemincrypto
          image: baemi
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 18080
              protocol: TCP
      imagePullSecrets:
        - name: ghcr
