name: ci

on:
  - push

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: Setup
        run: |
          git config --global url."https://${{ secrets.GH_ACCESS_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Checkout submodules
        shell: bash
        run: |
          # From https://github.com/actions/checkout/issues/116#issuecomment-583221947
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git submodule sync --recursive
          git -c "http.extraheader=Authorization: basic ${{secrets.GH_ACCESS_TOKEN}}" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Test with Gradle
        run: ./gradlew check
