name: ci

on:
  - push

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: Setup
        run: |
          git config --global url."https://${{ secrets.GH_ACCESS_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Initialize IDL git submodule
        run: make idl

      - name: Test with Gradle
        run: ./gradlew check
